### ISSUE TITLE
Google Chrome is the new Flash

### ISSUE THREAD

**Issue by pwalsh** [datproject/datfolder#347]
:(

Any plans to support non-GOOG browsers?

<img width="1280" alt="screenshot 2016-12-24 22 30 25" src="https://cloud.githubusercontent.com/assets/791678/21468685/b1efbbfe-ca28-11e6-8fb9-726b2c4202df.png">

**Comment by timdream** [comment]
It seems that this banner is designed to show itself with UA detection, instead of feature detection.

https://github.com/datproject/datfolder/pull/213/files#diff-3a421a66acbb65a143c30454a3a9ed61R5 #213 by @karissa 

The site currently shows warning on Firefox but it works fine. Maybe for now.

What's the required features for the site to work? I know it's WebRTC-based but I don't know what else. I am happy to contribute if it's something outside your paid time.

**Comment by yoshuawuyts** [comment]
iirc we should be moving onto websockets / some other method of uploading (e.g. dat-desktop) at some point so we can also get rid of that banner (:

**Comment by karissa** [comment]
Got it, definitely! Let's say it works in Firefox for now, because I agree that it does work in firefox, and if bug reports come up we will deal with them.

**Comment by karissa** [comment]
WebRTC support on Firefox is not working.

**Comment by karissa** [comment]
WebRTC support in Firefox is not working, so the browser-to-browser features won't work. But, the server features (like viewing the file list) from a remote archive shared from the commandline will work.

**Comment by karissa** [comment]
@timdream it'd be awesome to get some help with the firefox compatibility. Want to help with this issue? I just reopened it. https://github.com/datproject/datfolder/issues/138
